import Head from 'next/head'
import React from 'react'
import AboutOne from '../components/about/about_one'
import AboutTwo from '../components/about/about_two'
import styles from '../styles/about.module.css'
const About = () => {
  return (
    <>
      <Head>
        <title>About</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <main className=''>
        <AboutOne />
        <AboutTwo />
      </main>
    </>
  )
}

export default About