import React, { useState } from 'react'
import Head from 'next/head'
import Jumbotron from '../components/jumbotron'
// import FaqClosure from '../components/faqs/disclosure.component'
import FaqIndex from '../components/faqs/faq.component'


const Faqs = () => {

  const faqPost = [
    {
       id:1,
      labels: 'General questions',
      posts: [
        {
          id: 1,
          title: 'How do I top up my card?',
          body: 'Approach agents at any Top-up point across various terminals.Give them your Cowry card for top-up and make payment.Your card will be topped for you and you can use it for bus payments.',
        },
        {
          id: 2,
          title: 'Do I always need to tap out when I reach my destination?'
        },
        {
          id: 3,
          title: 'Does the Cowry card expire?'
        },
        {
          id: 4,
          title: 'Can two people use one card for a trip?'
        }, {
          id: 5,
          title: 'How do I get a replacement if I misplace my card?'
        }, {
          id: 6,
          title: 'Can I use my Cowry card to pay for shopping items?'
        }
      ]
    },
    {
      id: 2,
      labels: 'Card related issues',
      posts: [
        {
          id: 1,
          title: 'How do I top up my card?',
          body: 'Approach agents at any Top-up point across various terminals.Give them your Cowry card for top-up and make payment.Your card will be topped for you and you can use it for bus payments.',
        },
        {
          id: 2,
          title: 'Do I always need to tap out when I reach my destination?'
        }
      ]
    },
    {
      id : 3,
      labels: 'App related issues',
      posts: [
  
        {
          id: 3,
          title: 'Does the Cowry card expire?'
        },
        {
          id: 4,
          title: 'Can two people use one card for a trip?'
        }, {
          id: 5,
          title: 'How do I get a replacement if I misplace my card?'
        }, {
          id: 6,
          title: 'Can I use my Cowry card to pay for shopping items?'
        }
      ]
    }

  ]

  let [faqsPost] = useState(faqPost)
  return (
    <>
      <Head>
        <title>Faqs</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <main>
        <Jumbotron text="FAQs" />
        <section className='my-6'>
            <FaqIndex posts={faqsPost}/>
        </section>
      </main>
    </>
  )
}

export default Faqs