import React, { useState } from 'react'
import Head from 'next/head'
import Jumbotron from '../components/jumbotron'
// import FaqClosure from '../components/faqs/disclosure.component'
import FaqIndex from '../components/faqs/faq.component'
import axios from 'axios'

export const getStaticProps = async () => {
  const request = await fetch('https://cowry-website-portal-fhtk54mb6a-uc.a.run.app/api/faqs', {
    headers: {
      Authorization: 'Bearer dc9d252c2d58a8af15f95e305b1baceeed566d3f618ad2ded84b5a6e98d0ffdc94479435820ee67bf37b73e75e63f4ba428e1a53660c7a85e87ed3dac827066d4abf0765fc1356038a62b2a5a3b469d0cda2bf270ca38ee0f490891c046260e0db5d9d2f93cfc80bd956528d7872799289dc7baf4543f5e39def5aa74f67f375'
    }
  })
  const data = await request.json()

  return {
    props: {
      faqs: data?.data
    }
  }
}


const Faqs = (props) => {
  console.log(props)
  const faqPost = [
    {
      id: 1,
      labels: 'General questions',
      posts: [
        {
          id: 1,
          title: 'How do I top up my card?',
          body: 'Approach agents at any Top-up point across various terminals.Give them your Cowry card for top-up and make payment.Your card will be topped for you and you can use it for bus payments.',
        },
        {
          id: 2,
          title: 'Do I always need to tap out when I reach my destination?'
        },
        {
          id: 3,
          title: 'Does the Cowry card expire?'
        },
        {
          id: 4,
          title: 'Can two people use one card for a trip?'
        }, {
          id: 5,
          title: 'How do I get a replacement if I misplace my card?'
        }, {
          id: 6,
          title: 'Can I use my Cowry card to pay for shopping items?'
        }
      ]
    },
    {
      id: 2,
      labels: 'Card related issues',
      posts: [
        {
          id: 1,
          title: 'How do I top up my card?',
          body: 'Approach agents at any Top-up point across various terminals.Give them your Cowry card for top-up and make payment.Your card will be topped for you and you can use it for bus payments.',
        },
        {
          id: 2,
          title: 'Do I always need to tap out when I reach my destination?'
        }
      ]
    },
    {
      id: 3,
      labels: 'App related issues',
      posts: [

        {
          id: 3,
          title: 'Does the Cowry card expire?'
        },
        {
          id: 4,
          title: 'Can two people use one card for a trip?'
        }, {
          id: 5,
          title: 'How do I get a replacement if I misplace my card?'
        }, {
          id: 6,
          title: 'Can I use my Cowry card to pay for shopping items?'
        }
      ]
    }

  ]

  let [faqsPost] = useState(faqPost)
  return (
    <>
      <Head>
        <title>Faqs</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <main>
        <Jumbotron text="FAQs" />
        <section className='my-6'>
          <FaqIndex posts={faqsPost} />
        </section>
      </main>
    </>
  )
}

export default Faqs