import Head from 'next/head'
import Image from 'next/image'
import Banner from '../components/index/banner.component'
import Stat from '../components/index/stat.component'
import Partners from '../components/index/partners.component'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <main className=''>
         <Banner />
         <Stat />
         <Partners />
      </main>
    </>
  )
}
