import Head from 'next/head'
import React from 'react'
import Card from '../components/services/card.component'
const services = () => {
  const servicesData = [
    {
      title: 'Merchant Pay',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Tristique dapibus adipiscing pulvinar ante aliquam tristique interdum cum dui. ',
      img: './images/services/iPhone.svg',
      type: 'iphone',
      imgWidth: '',
      // layout : 'flex-row-reverse'
    },
    {
      title: 'Inter-state travel',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Tristique dapibus adipiscing pulvinar ante aliquam tristique interdum cum dui. ',
      img: './images/services/image_one.png',
      imgWidth: 'md:w-[500px]',
      layout: 'flex-row-reverse'

    },
    {
      title: 'FLM Scheme',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Tristique dapibus adipiscing pulvinar ante aliquam tristique interdum cum dui. ',
      img: './images/services/image_two.png',
      imgWidth: 'md:w-[500px]',
      // layout : ''
    },
    {
      title: 'Ferry',
      body: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Tristique dapibus adipiscing pulvinar ante aliquam tristique interdum cum dui.  ',
      img: './images/services/image_three.png',
      imgWidth: 'md:w-[500px]',
      layout: 'flex-row-reverse'
    },

  ]
  return (
    <>
      <Head>
        <title>Services</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <main className='px-3 py-10 md:px-auto md:py-20 '>
        {servicesData.map((data, id) => (
          <Card details={data} key={id} />
        ))}
      </main>
    </>
  )
}

export default services